# Generated by Django 3.0.3 on 2020-06-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='raindata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterytime', models.DateTimeField(default=True)),
                ('rain', models.FloatField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='rainstation',
            name='location',
        ),
        migrations.AlterField(
            model_name='rainstation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='volenteer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='volenteer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='volenteer',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Rain',
        ),
    ]
