# Generated by Django 3.0.3 on 2020-06-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainapp', '0002_auto_20200611_1459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rainstation',
        ),
    ]
