# Generated by Django 3.0.3 on 2020-06-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainapp', '0003_delete_rainstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raindata',
            name='enterytime',
            field=models.DateTimeField(),
        ),
    ]
