# Generated by Django 3.0.3 on 2020-06-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainapp', '0004_auto_20200611_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raindata',
            name='rain',
            field=models.IntegerField(max_length=10),
        ),
    ]
