# Generated by Django 3.0.3 on 2020-06-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainapp', '0005_auto_20200611_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raindata',
            name='rain',
            field=models.IntegerField(),
        ),
    ]
